siteTitle = "Empathetic Engineer"
siteDescr = "Building neat things."
siteAuthor = "Alex Kim"

siteLinkedInUrl = "https://www.linkedin.com/in/minseoalexkim"
siteGithubUrl = "https://github.com/minseokim"
siteEmailUrl = "minseosolve@gmail.com"
siteRssUrl = "#"

googleAnalyticsId = ""

linkPrefix = ""